CREATE TABLE login_users(
		ID				INT(10)	NOT NULL AUTO_INCREMENT PRIMARY KEY,
		username	VARCHAR(255)	NOT NULL,
		email			VARCHAR(255)	NOT NULL,
		password		VARCHAR(255)	NOT NULL,
		acountType	INT(10)	DEFAULT '1'
);
